
-- Step 1: Drop the name-only unique constraint that prevents tenant-specific profiles
ALTER TABLE public.access_profiles DROP CONSTRAINT access_profiles_name_unique;

-- Step 2: Add a composite unique constraint scoped to tenant_id
ALTER TABLE public.access_profiles ADD CONSTRAINT access_profiles_name_tenant_unique UNIQUE (name, tenant_id);

-- Step 3: Create default access profiles for Mica tenant
INSERT INTO public.access_profiles (name, description, permissions, tenant_id, is_active)
VALUES
  ('Admin', 'Acesso total à organização', '{"dashboard":{"view":true,"export":true},"membros":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"congregacoes":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"departamentos":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"ministerios":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"eventos":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"financeiro":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"conciliacoes":{"view":true,"insert":true,"edit":true,"delete":true,"approve":true,"export":true},"fornecedores":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"contas-pagar":{"view":true,"insert":true,"edit":true,"delete":true,"approve":true,"export":true},"relatorios":{"view":true,"export":true},"notificacoes":{"view":true,"insert":true,"edit":true,"delete":true,"send":true},"gestao-acessos":{"view":true,"insert":true,"edit":true,"delete":true,"approve":true},"documentacao":{"view":true,"insert":true,"edit":true,"delete":true,"export":true},"configuracoes":{"view":true,"edit":true}}', 'bf9bb59f-31a7-4c11-b23d-7a1d67d65af1', true),
  ('Pastor', 'Gestão da congregação com acesso financeiro', '{"dashboard":{"view":true,"export":true},"membros":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"congregacoes":{"view":true,"insert":false,"edit":false,"delete":false,"export":true},"departamentos":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"ministerios":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"eventos":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"financeiro":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"conciliacoes":{"view":true,"insert":true,"edit":true,"delete":false,"approve":false,"export":true},"fornecedores":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"contas-pagar":{"view":true,"insert":true,"edit":true,"delete":false,"approve":false,"export":true},"relatorios":{"view":true,"export":true},"notificacoes":{"view":true,"insert":false,"edit":false,"delete":false,"send":false},"gestao-acessos":{"view":false,"insert":false,"edit":false,"delete":false,"approve":false},"documentacao":{"view":true,"insert":false,"edit":false,"delete":false,"export":true},"configuracoes":{"view":false,"edit":false}}', 'bf9bb59f-31a7-4c11-b23d-7a1d67d65af1', true),
  ('Gerente Financeiro', 'Gestão financeira completa com aprovações', '{"dashboard":{"view":true,"export":true},"membros":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"congregacoes":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"departamentos":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"ministerios":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"eventos":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"financeiro":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"conciliacoes":{"view":true,"insert":true,"edit":true,"delete":false,"approve":true,"export":true},"fornecedores":{"view":true,"insert":true,"edit":true,"delete":false,"export":true},"contas-pagar":{"view":true,"insert":true,"edit":true,"delete":false,"approve":true,"export":true},"relatorios":{"view":true,"export":true},"notificacoes":{"view":false,"insert":false,"edit":false,"delete":false,"send":false},"gestao-acessos":{"view":false,"insert":false,"edit":false,"delete":false,"approve":false},"documentacao":{"view":true,"insert":false,"edit":false,"delete":false,"export":true},"configuracoes":{"view":false,"edit":false}}', 'bf9bb59f-31a7-4c11-b23d-7a1d67d65af1', true),
  ('Membro', 'Acesso básico de visualização', '{"dashboard":{"view":true,"export":false},"membros":{"view":false,"insert":false,"edit":false,"delete":false,"export":false},"congregacoes":{"view":false,"insert":false,"edit":false,"delete":false,"export":false},"departamentos":{"view":false,"insert":false,"edit":false,"delete":false,"export":false},"ministerios":{"view":false,"insert":false,"edit":false,"delete":false,"export":false},"eventos":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"financeiro":{"view":false,"insert":false,"edit":false,"delete":false,"export":false},"conciliacoes":{"view":false,"insert":false,"edit":false,"delete":false,"approve":false,"export":false},"fornecedores":{"view":false,"insert":false,"edit":false,"delete":false,"export":false},"contas-pagar":{"view":false,"insert":false,"edit":false,"delete":false,"approve":false,"export":false},"relatorios":{"view":false,"export":false},"notificacoes":{"view":false,"insert":false,"edit":false,"delete":false,"send":false},"gestao-acessos":{"view":false,"insert":false,"edit":false,"delete":false,"approve":false},"documentacao":{"view":true,"insert":false,"edit":false,"delete":false,"export":false},"configuracoes":{"view":false,"edit":false}}', 'bf9bb59f-31a7-4c11-b23d-7a1d67d65af1', true);

-- Step 4: Update Mica admin users to use the tenant-specific Admin profile
UPDATE public.profiles 
SET profile_id = (
  SELECT id FROM public.access_profiles 
  WHERE name = 'Admin' AND tenant_id = 'bf9bb59f-31a7-4c11-b23d-7a1d67d65af1'
  LIMIT 1
)
WHERE tenant_id = 'bf9bb59f-31a7-4c11-b23d-7a1d67d65af1' 
  AND role = 'admin';
