// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jryifbcsifodvocshvuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyeWlmYmNzaWZvZHZvY3NodnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzAwOTYsImV4cCI6MjA2NTc0NjA5Nn0.19evtStOEzVAbXX-Z27xi35JnTC7vd046EDRFrb9ETE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);